####################################################
##                                                ##
##  Build File for the                            ##
##             openSUSE Weekly News Project       ##
##                                                ##
##  Sascha Manns <saigkill@opensuse.org>          ##
##  Thomas Schraitle <toms@suse.de>               ##
####################################################

For this step we need two special package from the Build Service.
You need the packages "susedoc" & "susedoc-buildbook". Both packages
have depencies to other needed packages like fop. That's ok. We
need all of this.

Then we have prepared a Script for exporting XML to PDF through FO.
Just run "xml2pdf.sh" in the shell. The next steps should run
automaticly through the Script. The result is a PDF File called OWN.pdf.

That file you can distribute on every place.

ATM we are working on more Outputformats.
